# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql_queries/:/docker-entrypoint-initdb.d

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ./metabase_data/:/metabase-data
    depends_on:
      - db
    links:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
