# Use postgres/example user/password credentials
version: '3.1'

services:

  metabase-db:
    image: postgres:14
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase_pass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  db:
    image: postgres:14
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql_queries/:/docker-entrypoint-initdb.d

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      - metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_pass
      MB_DB_HOST: metabase-db

    depends_on:
      - db
      - metabase-db
    links:
      - db
      - metabase-db

    healthcheck:
      test: curl --fail localhost:3001/api/health || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pgdata:
  metabase-data:
