version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
