version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .prodcontainer/prod.Dockerfile
    network_mode: service:db
    command: python -m src.main
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      timeout: 45s
      interval: 10s
      retries: 10

    ports:
      - "5432:5432"
